server:
  port: 8081
spring:
  application:
    name: ResourceServer

  security:
    oauth2:
      resourceserver:
        issuer-uri: http://localhost:9190/realms/test-realm
        jwk-set-uri: http://localhost:9190/realms/test-realm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            issuer: http://localhost:9190/realms/test-realm
            provider: keycloak
            client-id: test-client
            client-secret: TYkk7QPQLCNXVQIcFOXBdaHaHjXJ5awt
            scope:
              - openid
            authorization-grant-type: authorization-code
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:9190/realms/test-realm
            authorization-uri: http://localhost:9190/realms/test-realm/protocol/openid-connect/auth
            token-uri: http://localhost:9190/realms/test-realm/protocol/openid-connect/token
            user-info-uri: http://localhost:9190/realms/test-realm/protocol/openid-connect/userinfo