server:
  port: 8081
spring:
  application:
    name: resource-server
  config:
    import: configserver:http://localhost:8888
#    import: optional:configserver://localhost:8888     if configuration is optional