server:
  port: 8081
spring:
  application:
    name: ResourceServer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9190/realms/test-realm
          jwk-set-uri: http://localhost:9190/realms/test-realm/protocol/openid-connect/certs # to validate token

  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/